### ISSUE TITLE
Мой отчет о результатах коммита

### ISSUE THREAD

**Issue by honia19** [honia19/comple#1]
Кирилл Викторович киньте мне запрос на Collaborate
Смотрите в репозитории comple
Видео по которому я работал: https://www.youtube.com/watch?v=ypA8JxP4z9M
И парочку скринов,с первым коммитом где пустое тело класса и 2 коммит где я его заполнил не сразу получилось к сожалению(((
[Смоктийскрины.docx](https://github.com/honia19/comple/files/288332/default.docx)

**Comment by Smoktii** [comment]
ок

**Comment by honia19** [comment]
Ok

**Comment by honia19** [comment]
Вы не поставили отметку в файле тхт репозитория comple.
